test_api:
  path: /testing
  controller: App\Controller\TestApiController::api
  methods: GET|POST

list_student_class:
  path: /classes
  controller: App\Controller\UserController::getStudentClassListing
  methods: GET

file_upload:
  path: /upload
  controller: App\Controller\SubmissionController::handleFileUpload
  methods: POST

register_student:
  path: /register-student
  controller: App\Controller\UserController::register
  methods: POST

post_homework:
  path: /post-homework
  controller: App\Controller\SubmissionController::postHomework
  methods: POST

list_active_hw:
  path: /list-class-hw
  controller: App\Controller\SubmissionController::getAllActiveHomework
  methods: POST

retrieve_user_class:
  path: /user-registered-class
  controller: App\Controller\UserController::getUserClass
  methods: GET

homework_details:
  path: /homework
  controller: App\Controller\SubmissionController::isolateHomework
  methods: POST

process_hw_submission:
  path: /process-homework-submission
  controller: App\Controller\SubmissionController::processHomeworkSubmission
  methods: POST

test_upload:
  path: /test-upload
  controller: App\Controller\SubmissionController::testFileUpload
  methods: POST

upload:
  path: /upload-homework
  controller: App\Controller\SubmissionController::handleFileUpload
  methods: POST

api_login_check:
  path: /login_check
